### ISSUE TITLE
Extra Credit - CloudWatch Logs VPC endpoint does not exist, no egress security group rules for S3 VPC endpoint

### ISSUE THREAD

**Issue by joshuapmorgan** [cassiamartin/cloud_native_infrasec#2]
Once S3 bucket storage and CloudWatch log stream is enabled within Systems Manager Session Manager, Session Manager sessions fail to connect. This is because there is no network path to CloudWatch Logs API endpoint and the traffic to S3 (via the Gateway VPC endpoint) is discarded by the EC2 instance security group (lack of matching egress rules).

**Comment by cassiamartin** [comment]
Pull request merged in.  Thanks for doing this work!
